# Generated by Django 3.0.6 on 2020-06-13 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PassPer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pass_name', models.CharField(max_length=30)),
                ('pass_address', models.CharField(max_length=30)),
                ('user_name', models.CharField(max_length=30)),
                ('user_starttime', models.CharField(max_length=30)),
                ('user_stoptime', models.CharField(max_length=30)),
                ('img', models.ImageField(null=True, upload_to='img_dir/')),
                ('sys_user_name', models.CharField(max_length=30)),
                ('final_result', models.BooleanField(default=False, null=True)),
            ],
        ),
    ]
