# Generated by Django 3.0.6 on 2020-06-13 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DayShare',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('share_time', models.DateTimeField(auto_now=True)),
                ('username', models.CharField(max_length=30, null=True)),
                ('share_text', models.TextField()),
            ],
        ),
    ]
